name: Build container

on: push

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build (no push)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: false
